version: 2.1
orbs:
  node: circleci/node@7.2.1
  win: circleci/windows@5.1.1
  macos: circleci/macos@2.4.1
parameters:
  main_node_version:
    type: string
    default: 18.20.8
workflows:
  build:
    
    jobs:
      #################################
      # CANARY BUILD/TEST
      # - For normal commits, run a single build with no binary publishing
      #################################
      - build:
          matrix:
            alias: canary_build
            parameters:
              os: [linux]
              arch: [x64]
              build-type: ["Debug"]
              node-version: [<< pipeline.parameters.main_node_version >>]
      - test:
          requires: [canary_build]
          matrix:
            alias: canary_test
            parameters:
              os: [linux]
              arch: [x64]
              build-type: ["Debug"]
              node-version:
                - << pipeline.parameters.main_node_version >>
                - "22.23.1"
                - "26.5.0"
      #################################
      # RELEASE BUILD/TEST
      # - For normal commits, run a single build with no binary publishing
      #################################
      - build:
          requires: [canary_test]
          filters: { branches: { ignore: /.*/ }, tags: { only: /^v.*/ } }
          matrix:
            alias: build_release
            parameters:
              os: [linux, windows, darwin]
              arch: [x64, arm64]
              node-version: [<< pipeline.parameters.main_node_version >>]
              build-type: ["Debug", "Release"]
              #build-type: ["Debug", "Release"]
            exclude:
              - { os: linux, arch: x64, build-type: Debug } # already done by the canary build
              - { os: darwin, arch: x64 }
              - { os: windows, arch: arm64 }
      - test:
          filters: { branches: { ignore: /.*/ }, tags: { only: /^v.*/ } }
          requires: [build_release]
          matrix:
            alias: test_release
            parameters:
              os: [linux, windows, darwin]
              arch: [x64, arm64]
              node-version:
                - << pipeline.parameters.main_node_version >>
                - "22.23.1"
                - "26.5.0"
              build-type: ["Debug"]
            exclude:
              - { os: darwin, arch: x64 }
              - { os: windows, arch: arm64 }
      - approve_publishing:
          type: approval
          requires: [test_release]
      - publish_binary_release:
          matrix:
            parameters:
              os: [linux, windows, darwin]
              arch: [x64, arm64]
              node-version: ["18.20.8"]
              build-type: ["Debug", "Release"]
            exclude:
              - { os: darwin, arch: x64 }
              - { os: windows, arch: arm64 }
          context: "@/webrtc/binaries"
          requires: [approve_publishing]

executors:
  linux-x64:
    docker:
      - image: ubuntu:26.04
    environment:
      TARGET_ARCH: x64
      CMAKE_BUILD_TYPE: Release
      PLATFORM: linux
    resource_class: xlarge
  linux-arm64:
    machine:
      image: ubuntu-2604:current
    resource_class: arm.medium
    environment:
      TARGET_ARCH: arm64
      CMAKE_BUILD_TYPE: Release
      PLATFORM: linux
  windows-x64:
    machine:
      image: windows-default
    resource_class: medium
    environment:
      PLATFORM: windows
  windows-arm64:
    machine:
      image: windows-default
    resource_class: arm.medium
    environment:
      PLATFORM: windows
  darwin-arm64:
    macos:
      xcode: "14.0.0"
    resource_class: m4pro.medium
    environment:
      TARGET_ARCH: x64
      CMAKE_BUILD_TYPE: Release
      PLATFORM: darwin
  darwin-x64:
    macos:
      xcode: "14.0.0"
    resource_class: m4pro.medium
    environment:
      TARGET_ARCH: x64
      CMAKE_BUILD_TYPE: Release
      PLATFORM: darwin
jobs:
  build:
    parameters:
      node-version: { type: string }
      os:           { type: string }
      arch:         { type: string }
      build-type:   { type: string }
    executor: "<< parameters.os >>-<< parameters.arch >>"
    working_directory: ~/node-webrtc
    steps:
      - configure_builds:
          build-type: <<parameters.build-type>>
      - platform_setup:
          os: <<parameters.os>>
      - node/install: { node-version: "<< parameters.node-version >>" }
      - setup_workspace
      - checkout
      - run: 
          name: Restore file modification timestamps for faster build
          command: git restore-mtime
      - setup_cache_key
      - npm_install
      - configure_parallelism: { value: "8" }
      - build_addon
      - store_binary:
          os: << parameters.os >>
          arch: << parameters.arch >>
          build-type: << parameters.build-type >>
  test:
    parameters: 
      node-version: { type: string }
      os:           { type: string }
      arch:         { type: string }
      build-type:   { type: string }
    executor: << parameters.os >>-<< parameters.arch >>
    steps:
      - platform_setup:
          os: <<parameters.os>>
      - node/install: { node-version: "<< parameters.node-version >>" }
      - setup_workspace
      - checkout
      - setup_cache_key
      - npm_install
      - run: 
          name: Build Typescript
          command: npm run build:tsc
      - acquire_binary:
          os: << parameters.os >>
          arch: << parameters.arch >>
          build-type: << parameters.build-type >>
      - run_tests

  publish_binary_release:
    parameters:
      node-version: { type: string }
      os:           { type: string }
      arch:         { type: string }
      build-type:   { type: string }
    executor: linux-x64
    steps:
      - platform_setup:
          os: <<parameters.os>>
      - node/install: { node-version: "<< parameters.node-version >>" }
      - setup_workspace
      - checkout
      - setup_cache_key
      - npm_install
      - run: 
          name: Build Typescript
          command: npm run build:tsc
      - acquire_binary:
          os: << parameters.os >>
          arch: << parameters.arch >>
          build-type: << parameters.build-type >>
      - publish_binary

commands:
  ###
  # SETUP WORKSPACE
  ###
  setup_workspace:
    description: Setup Workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace
  build_addon:
    description: Build @/webrtc
    steps:
      - restore_cache:
          name: Restore cached libwebrtc build
          key: asset-cache-v5-{{ arch }}-{{ checksum "CACHE_KEY" }}-{{ checksum "CMakeLists.txt" }}
      - run:
          name: Build libwebrtc + Node.js bindings
          command: npm run build:native
      - run: 
          name: Build Typescript
          command: npm run build:tsc
      - save_cache:
          name: Saving build cache
          key: asset-cache-v5-{{ arch }}-{{ checksum "CACHE_KEY" }}-{{ checksum "CMakeLists.txt" }}
          paths:
            - build
            - ~/.cache/ccache
            - ~/.ccache
  ###
  # NPM INSTALL
  ###
  npm_install:
    description: npm install
    steps:
      - restore_cache:
          name: Restore cached NPM modules
          key: modules-cache-v2-{{ arch }}-{{ checksum "CACHE_KEY" }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          name: Cache NPM modules
          key: modules-cache-v2-{{ arch }}-{{ checksum "CACHE_KEY" }}-{{ checksum "package.json" }}
          paths:
            - node_modules
  ###
  # PUBLISH BINARY
  ###
  publish_binary:
    description: Publish binary to CDN
    steps:
      - run:
          name: Publish Binary
          command: |
            npm run publish-binary
  ###
  # TEST ELECTRON
  ###
  test_electron:
    description: Test Electron
    steps:
      - run:
          name: Test Electron
          command: |
            if [[ "$(uname)" == Linux ]]; then
              xvfb-run ./node_modules/.bin/electron dist/nodejs/test/electron/index.js --no-sandbox
            else
              npm run test:electron
            fi
  setup_cache_key:
    description: Set up a cache key variable used to invalidate build caches
    steps:
      - run:
          name: Before restore cache...
          command: |
            echo >>CACHE_KEY "TARGET_ARCH=$TARGET_ARCH"
            echo >>CACHE_KEY "CMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE"
            echo >>CACHE_KEY "TARGET_PLATFORM=$TARGET_PLATFORM"
            cat CACHE_KEY
  cpp_tests:
    steps:
      - run:
          name: Run C++ unit tests
          command: |
            if [[ "$CMAKE_BUILD_TYPE" == Debug ]]; then
              node dist/nodejs/test/cpp-test.js
            else
              echo "Skipping C++ unit tests (not available on a release build)"
            fi
  unit_tests:
    steps:
      - run:
          name: Run Unit and Integration Tests
          command: |
            export CHECK_REFLEXIVE=true
            npm test -- --runInBand --verbose --ci
  ###
  # ARM UNIT TESTS (in emulator)
  ###
  arm_unit_tests:
    steps:
      - run:
          name: Run Unit and Integration Tests
          command: |
            export NODE_VERSION=$(node -v | tr -d '\n')
            export CHECK_REFLEXIVE=true
            qemu-aarch64 -L ~/node-webrtc/build/external/libwebrtc/download/src/build/linux/debian_sid_arm64-sysroot ~/node-$NODE_VERSION-linux-arm64/bin/node node_modules/.bin/jest
  ###
  # WEB PLATFORM TESTS
  ###
  wpt_tests:
    steps:
      - run:
          name: Setup /etc/hosts for Web Platform Tests (x64-only)
          command: |
            cat ci/wpt-hosts >>/etc/hosts
      - run:
          name: Run Web Platform Tests (x64-only)
          command: |
            if [[ "$TARGET_ARCH" == arm* ]]; then
              echo "Skipping..."
              exit 0
            fi

            if [[ "$(uname)" == Linux ]]; then
              sudo apt install --reinstall python-pkg-resources
              #pip install --upgrade requests
            fi

            npm run wpt:init
            npm run wpt:test
  ###
  # RUN BROWSER TESTS
  ###
  browser_tests:
    steps:
      - run:
          name: Browser Tests
          command: |
            npm run test:browser
  ###
  # STORE BUILD FOR LATER USE
  ###
  store_binary:
    parameters:
      os: { type: string }
      arch: { type: string }
      build-type: { type: string }
    steps:
      - run:
          name: Store binary (.../<<parameters.os>>-<<parameters.arch>>-<<parameters.build-type>>/wrtc.node)
          command: |
            mkdir -p /tmp/workspace/<<parameters.os>>-<<parameters.arch>>-<<parameters.build-type>>
            cd /tmp/workspace/<<parameters.os>>-<<parameters.arch>>-<<parameters.build-type>>
            cp ~/node-webrtc/build/<<parameters.build-type>>/wrtc.node wrtc.node
      - store_artifacts:
          path: /tmp/workspace/<<parameters.os>>-<<parameters.arch>>-<<parameters.build-type>>/wrtc.node
          destination: <<parameters.os>>-<<parameters.arch>>-<<parameters.build-type>>/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"
  acquire_binary:
    description: Acquire Binary
    parameters:
      os: { type: string }
      arch: { type: string }
      build-type: { type: string }
    steps:
      - run:
          name: Acquire Binary (<<parameters.os>>-<<parameters.arch>>-<<parameters.build-type>>)
          command: |
            rm -Rf build/Release build/Debug
            mkdir -p build/<<parameters.build-type>>
            cp /tmp/workspace/<<parameters.os>>-<<parameters.arch>>-<<parameters.build-type>>/wrtc.node build/<<parameters.build-type>>/
  ###
  # PLATFORM-SPECIFIC INSTALLATIONS
  ###
  platform_setup:
    parameters:
      os: { type: string }
    steps:
      ###
      # MACOS SPECIFIC SETUP
      ###
      - when:
          condition: { equal: [ darwin, << parameters.os >> ] }
          steps:
            - macos/install-rosetta
            - set_env_var:
                label: Set target platform
                var: TARGET_PLATFORM
                value: darwin
            - run:
                name: Install build tools
                command: brew install cmake kamilturek/python2/python@2 ccache
      ###
      # WINDOWS SPECIFIC SETUP
      ###
      - when:
          condition: { equal: [ windows, << parameters.os >> ] }
          steps:
            - set_env_var:
                label: Set target platform
                var: TARGET_PLATFORM
                value: windows
            - run:
                name: Install CMake, Python, Windows 10 SDK
                command: |
                  choco install -y cmake python windows-sdk-10-version-2004-all sccache --no-progress
                  cp /c/tools/miniconda3/python.exe /c/tools/miniconda3/python3.exe # gn depends on python3 alias
      ###
      # LINUX SPECIFIC SETUP
      ###
      - when:
          condition: { equal: [ linux, << parameters.os >> ] }
          steps:
            - set_env_var:
                label: Set target platform
                var: TARGET_PLATFORM
                value: linux
            - run:
                name: Install platform dependencies
                command: |
                  apt update
                  ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
                  DEBIAN_FRONTEND=noninteractive apt install -y tzdata
                  dpkg-reconfigure --frontend noninteractive tzdata
                  apt install -y \
                      sudo lsb-release software-properties-common gnupg wget cmake build-essential curl git \
                      python3 python3-pkg-resources libglib2.0-dev ninja-build libnspr4 libnss3 \
                      libatk1.0-0 libatk-bridge2.0-0 libcups2 libcairo2 libgtk-3-0 libasound2t64 xvfb ccache \
                      git-restore-mtime
                  curl https://apt.llvm.org/llvm.sh >/tmp/llvm.sh
                  chmod +x /tmp/llvm.sh
                  sudo /tmp/llvm.sh 23
                  sudo ln -s `which python3` /usr/local/bin/python
                  sudo ln -s `which clang-23` /usr/local/bin/clang
                  sudo ln -s `which clang++-23` /usr/local/bin/clang++
            - run:
                name: Toolchain versions
                command: |
                  set -x
                  clang --version
                  cmake --version
                  ninja --version
  ###
  # UTILITY: SET ENVIRONMENT VARIABLE
  # - Ensures the environment variable will be available for subsequent steps
  ###
  set_env_var:
    parameters:
      label:
        type: string
      var:
        type: string
      value:
        type: string
    steps:
      - run:
          name: << parameters.label >>
          command: echo 'export << parameters.var >>="<< parameters.value >>"' >> $BASH_ENV
  ###
  # CONFIGURE DEBUG BUILDS
  ###
  configure_builds:
    parameters:
      build-type: { type: string }
    steps:
      - when:
          condition:
            equal: [ "Debug", << parameters.build-type >> ]
          steps:
            - set_env_var:
                label: Set CMake build type (Debug)
                var: CMAKE_BUILD_TYPE
                value: Debug
            - set_env_var:
                label: Set DEBUG=true
                var: DEBUG
                value: "true"
  configure_parallelism:
    parameters:
      value:
        type: string
    steps:
      - set_env_var: { label: "Configure parallelism", var: PARALLELISM, value: "<< parameters.value >>" }
  run_tests:
    steps:
      - run: ulimit -c unlimited
      - cpp_tests
      - unit_tests
      # - wpt_tests
      - browser_tests
      - test_electron
      - run:
          command: |
            mkdir -p /tmp/core_dumps
            cp core.* /tmp/core_dumps
            cp report.*.json /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps